services:
  - type: web
    name: myhospital-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn myhospital.wsgi:application"
    envVars:
      - key: DATABASE_URL
        value: sqlite:///db.sqlite3
