services:
  - type: web
    name: myhospital-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn myhospital.wsgi:application
    plan: free
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: myhospital.settings
